# Generated by Django 5.1.1 on 2024-09-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='auctioner',
        ),
        migrations.AddField(
            model_name='user',
            name='auctions',
            field=models.ManyToManyField(related_name='auctioner', to='auctions.listing'),
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(related_name='followers', to='auctions.listing'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
